<? php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<title>Senior Design Mars Project</title>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<style>';
echo 'a {';
echo 'text-decoration: none;';
echo '}';
echo '';
echo 'body,';
echo 'h1,';
echo 'h2,';
echo 'h3,';
echo 'h4,';
echo 'h5,';
echo 'h6 {';
echo 'font-family: "Montserrat", sans-serif';
echo '}';
echo '';
echo '.w3-row-padding img {';
echo 'margin-bottom: 12px';
echo '}';
echo '';
echo '/* Set the width of the sidebar to 120px */';
echo '.w3-sidebar {';
echo 'width: 120px;';
echo 'background: #222;';
echo '}';
echo '';
echo '/* Add a left margin to the "page content" that matches the width of the sidebar (120px) */';
echo '#main {';
echo 'margin-left: 120px';
echo '}';
echo '';
echo '/* Remove margins from "page content" on small screens */';
echo '@media only screen and (max-width: 600px) {';
echo '#main {';
echo 'margin-left: 0';
echo '}';
echo '}';
echo '';
echo '</style>';
echo '';
echo '<body class="w3-black">';
echo '';
echo '<!-- Icon Bar (Sidebar - hidden on small screens) -->';
echo '<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">';
echo '<!-- Avatar image in top left corner -->';
echo '<img src="images/CSUNS.svg.png" style="width:100%; opacity: 0.2; ">';
echo '<a href="#" class="w3-bar-item w3-button w3-padding-large w3-black">';
echo '<i class="fa fa-home w3-xxlarge"></i>';
echo '<p>HOME</p>';
echo '</a>';
echo '<a href="#about" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-user w3-xxlarge"></i>';
echo '<p>ABOUT</p>';
echo '</a>';
echo '<a href="#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-eye w3-xxlarge"></i>';
echo '<p>PHOTOS</p>';
echo '</a>';
echo '<a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hover-black">';
echo '<i class="fa fa-envelope w3-xxlarge"></i>';
echo '<p>CONTACT</p>';
echo '</a>';
echo '</nav>';
echo '';
echo '<!-- Navbar on small screens (Hidden on medium and large screens) -->';
echo '<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">';
echo '<div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">';
echo '<a href="#" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>';
echo '<a href="#about" class="w3-bar-item w3-button" style="width:25% !important">ABOUT</a>';
echo '<a href="#photos" class="w3-bar-item w3-button" style="width:25% !important">PHOTOS</a>';
echo '<a href="#contact" class="w3-bar-item w3-button" style="width:25% !important">CONTACT</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Page Content -->';
echo '<div class="w3-padding-large" id="main">';
echo '<!-- Header/Home -->';
echo '<header class="w3-container w3-padding-32 w3-center w3-black" id="home">';
echo '<h1 class="w3-jumbo"><span class="w3-hide-small">We are</span> Mars.</h1>';
echo '<p>Senior Design Fall 2019.</p>';
echo '<img src="images/14678.jpg" alt="Mars" class="images" width="1000" height="700">';
echo '</header>';
echo '';
echo '<!-- About Section -->';
echo '<div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">';
echo '<h2 class="w3-text-light-grey">About Us</h2>';
echo '<hr style="width:200px" class="w3-opacity">';
echo '<p>We are a group of five students, just trying to graduate and get successfull jobs. We are in our Senior year of school at CSUN and all plan to graduate in spring 2020.';
echo '</p>';
echo '<h3 class="w3-padding-16 w3-text-light-grey">Our Skills</h3>';
echo '<p class="w3-wide">Web design</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:45%"></div>';
echo '</div>';
echo '<p class="w3-wide">Security</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:55%"></div>';
echo '</div>';
echo '<p class="w3-wide">AWS</p>';
echo '<div class="w3-white">';
echo '<div class="w3-dark-grey" style="height:28px;width:25%"></div>';
echo '</div><br>';
echo '';
echo '<div class="w3-row w3-center w3-padding-16 w3-section w3-light-grey">';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">5</span><br>';
echo 'Partners';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">3+</span><br>';
echo 'Projects Done';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">50+</span><br>';
echo 'Happy Teachers';
echo '</div>';
echo '<div class="w3-quarter w3-section">';
echo '<span class="w3-xlarge">150+</span><br>';
echo 'Hours in School';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!-- Testimonials -->';
echo '<h3 class="w3-padding-24 w3-text-light-grey">The Team</h3>';
echo '<img src="images/edwin.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Edwin Burgos.</span> Student at Cal State Northridge.</p>';
echo '<p>Edwin is majoring in CIT.</p><br>';
echo '';
echo '<img src="images/justina.jpeg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Justina Chapman.</span> Student at Cal State Northridge.</p>';
echo '<p>CIT is her passion.</p><br>';
echo '';
echo '<img src="images/Cory.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Cory Ethridge.</span> Student at Cal State Northridge.</p>';
echo '<p>Intrested in Cyber Security.</p><br>';
echo '';
echo '<img src="images/" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Daniel Parks.</span> Student at Cal State Northridge.</p>';
echo '<p>Random ish about Daniel.</p><br>';
echo '';
echo '<img src="images/" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">';
echo '<p><span class="w3-large w3-margin-right">Mikayel Mansuryan.</span> Student at Cal State Northridge.</p>';
echo '<p>Random ish about Mikayel.</p><br>';
echo '';
echo '';
echo '<!-- End About Section -->';
echo '</div>';
echo '';
echo '<!-- Portfolio Section -->';
echo '<div class="w3-padding-64 w3-content" id="photos">';
echo '<h2 class="w3-text-light-grey">Photos of Mars</h2>';
echo '<hr style="width:300px" class="w3-opacity">';
echo '';
echo '<!-- Grid for photos -->';
echo '<div class="w3-row-padding" style="margin:0 -16px">';
echo '<div class="w3-half">';
echo '<img src="images/190405-mars-habitats-mn-1145_copy_399a850298539113439423152c7a38eb.fit-1240w.jpg" style="width:100%">';
echo '<img src="images/538127.jpg" style="width:100%">';
echo '<img src="images/q2buoulie0lwceikq5m6.jpg" style="width:100%">';
echo '<img src="images/ZZ55SdKdURaoVqczJTDoJ7-650-80.jpg" style="width:100%">';
echo '</div>';
echo '';
echo '<div class="w3-half">';
echo '<img src="images/465953.jpg" style="width:100%">';
echo '<img src="images/538207.jpg" style="width:100%">';
echo '<img src="images/mars_web-thumb-large.jpg" style="width:100%">';
echo '<img src="images/marsimpactcrater_1024.jpg" style="width:100%">';
echo '</div>';
echo '<!-- End photo grid -->';
echo '</div>';
echo '<!-- End Portfolio Section -->';
echo '</div>';
echo '';
echo '<!-- Contact Section -->';
echo '<div class="w3-padding-64 w3-content w3-text-grey" id="contact">';
echo '<h2 class="w3-text-light-grey">Contact Me</h2>';
echo '<hr style="width:200px" class="w3-opacity">';
echo '';
echo '<div class="w3-section">';
echo '<p><i class="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Northridge, US</p>';
echo '<p><i class="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Phone: +1 888 123-456</p>';
echo '<p><i class="fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i> Email: csunmars@gmail.com</p>';
echo '</div><br>';
echo '<p>Lets get in touch. Send me a message:</p>';
echo '';
echo '<form action="mailto:csunmars@gmail.com" method="post" enctype="multipart/form-data">';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Name" required name="Name"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Email" required name="Email"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Subject" required name="Subject"></p>';
echo '<p><input class="w3-input w3-padding-16" type="text" placeholder="Message" required name="Message"></p>';
echo '<p>';
echo '<button class="w3-button w3-light-grey w3-padding-large" type="submit">';
echo '<i class="fa fa-paper-plane"></i> SEND MESSAGE';
echo '</button>';
echo '</p>';
echo '</form>';
echo '<!-- End Contact Section -->';
echo '</div>';
echo '';
echo '';
echo '<div>';
echo '';
echo '<!-- Footer -->';
echo '<footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">';
echo '<a href="https://github.com/V1ndl3R/MARS" title="Mars Github>" <i class="fa fa-github-square w3-hover-opacity"></i></a>';
echo '';
echo '<p class="w3-medium">Stolen from <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>';
echo '<!-- End footer -->';
echo '</footer>';
echo '';
echo '<!-- END PAGE CONTENT -->';
echo '</div>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>